import Head from "next/head";
import Appbar from "./components/appbar/Appbar";
import HomePage from "./components/HomePage/homePage";



export default function Home() {
  return (
    <>
      <Head>
        <title>SBB</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <main>
        <Appbar />
        <HomePage />
      </main>
    </>
  );
}
